language: objective-c
xcode_workspace: AmericanChronicle.xcworkspace
xcode_scheme: AmericanChronicle
osx_image: xcode8

script:
  xcodebuild \
      CODE_SIGNING_REQUIRED=NO \
      CODE_SIGN_IDENTITY= \
      PROVISIONING_PROFILE= \
      -sdk iphonesimulator \
      -destination 'platform=iOS Simulator,OS=latest' \
      -workspace AmericanChronicle.xcworkspace \
      -scheme "AmericanChronicle" \
      test